### ISSUE TITLE
Support import bts json wallet, for claiming bts snapshot, generate a new genesis

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#44]
Other than pts/btc, we need a new import support for bts

**Comment by clar** [comment]
added wallet_import_bitshares api
next is to honor the bts snaphot in genesis init

**Comment by HackFisher** [comment]
@clar final check, is bts_20141208.json ags_20140718.json pts_20141105.json the right one? gona to generate the final genesis json

**Comment by clar** [comment]
yes, in below folder
https://github.com/bitsuperlab/bitshares_play/tree/develop/libraries/blockchain/pts_ags_snapshot

**Comment by HackFisher** [comment]
@clar importing DNS to BTS for collecting vesting shares, could be as reference.

**Comment by HackFisher** [comment]
refer http://www.btc38.com/altcoin/bts/5863.html

**Comment by clar** [comment]
got it. yes, it's very similar to importing DNS.

**Comment by clar** [comment]
seems we already have a wallet_import_keys_from_json api to import bts wallet, so the new api is not needed, i'll test it.

**Comment by clar** [comment]
currently wallet_import_keys_from_json has some issue , it's alway failed to import keys which is fixed 
https://github.com/bitsuperlab/bitshares_play/commit/48859575864b911aed4d180afa8dbfde360d8c0b

needed to push to bts.

**Comment by HackFisher** [comment]
@clar so is play ok to import now? and bts still have this issue, need to provide a pull request to them?

**Comment by clar** [comment]
should work on play now, i'll test a wallet with balance today. Bts dev branch has this issue, last night I failed to compile with the latest codes, so not create a pull request.

**Comment by HackFisher** [comment]
OK, then put a link to bitshares wallet_import_keys_from_json issue, just incase we forget to submit a pull request later, https://github.com/BitShares/bitshares/issues/1219

**Comment by clar** [comment]
https://github.com/BitShares/bitshares/issues/1297 is also tracking the import issue, and it has been fixed on latest dev branch.

**Comment by HackFisher** [comment]
@clar Do we need to merge that commit?
